FROM ecolell/python:3.7.2 AS python
RUN pip -V

FROM ecolell/node:8.11.1 AS node
RUN npm -v && yarn -v

MAINTAINER Eloy Adonis Colell <eloy.colell@gmail.com>

RUN mkdir /var/stage
EXPOSE 8000 5000 2992
VOLUME ["/var/stage"]
