FROM julia:0.4.6 as julia
FROM ecolell/flask-test-server:py3.7.3_n8.11.1

COPY --from=julia /usr/local/julia/* /usr/local/julia/
COPY --from=julia /usr/local/julia/bin/* /usr/local/julia/bin/

MAINTAINER Eloy Adonis Colell <eloy.colell@gmail.com>

ARG DEBIAN_FRONTEND=noninteractive

# ENV ALGORITHMS_PACKAGES freecontact rabbitmq-server

ENV PATH="${PATH}:/usr/local/julia/bin:/CCMpred/bin"
# /julia-ae26b25d43/bin
# install apt
RUN apk add --upgrade util-linux binutils binutils-gold clang cmake postgresql
# RUN apt-get update && apt-get install -y apt-utils postgresql
# RUN apt-get install -y $ALGORITHMS_PACKAGES

# install freecontact
RUN apk add boost-dev gfortran lapack-dev make

RUN wget ftp://rostlab.org/free/freecontact-1.0.21.tar.xz && \
    tar xfvv freecontact-1.0.21.tar.xz && \
    cd freecontact-1.0.21 && \
    ./configure

RUN apk del boost-dev gfortran lapack-dev make

# install ccmpred
RUN git clone --recursive https://github.com/soedinglab/CCMpred.git && \
    cd CCMpred && \
    cmake . && make

# update to julia 0.4
#RUN wget https://julialang-s3.julialang.org/bin/linux/x64/0.4/julia-0.4.7-linux-x86_64.tar.gz && \
#    tar -zxvf julia-0.4.7-linux-x86_64.tar.gz && \
#    rm -rf julia-0.4.7-linux-x86_64.tar.gz
# install MIToS.js inside julia
RUN julia -e 'Pkg.clone("https://github.com/ecolell/GaussDCA.jl"); Pkg.update(); Pkg.add("MIToS"); Pkg.pin("MIToS", v"1.2.3"); Pkg.update()'
# install psicov
RUN wget http://bioinfadmin.cs.ucl.ac.uk/downloads/PSICOV/psicov2.c && gcc -m64 -Ofast -march=native -fopenmp psicov2.c -lm -o psicov && chmod u+x psicov && mv psicov /usr/bin/

EXPOSE 4369 5555
