FROM ecolell/git-lfs:alpine3.9.4 as gitlfs
FROM node:10.16.0-alpine as node
COPY --from=0 /usr/bin /usr/bin
COPY --from=0 /lib/ld-musl-x86_64.so.1 /lib/
COPY --from=0 /usr/lib/libpcre2-8.so.0 /usr/lib/
COPY --from=0 /lib/libz.so.1 /lib/
COPY --from=0 /lib/libc.musl-x86_64.so.1 /lib/

MAINTAINER Eloy Adonis Colell <eloy.colell@gmail.com>