FROM python:3.6.8-alpine3.9 as python
MAINTAINER Eloy Adonis Colell <eloy.colell@gmail.com>

COPY \
    --from=ecolell/git-lfs:alphine3.9.4 \
    /usr/bin/git* /usr/bin/
COPY \
    --from=ecolell/git-lfs:alphine3.9.4 \
    /usr/lib/lib* /usr/lib/
COPY \
    --from=ecolell/git-lfs:alphine3.9.4 \
    /usr/libexec/git-core/* /usr/libexec/git-core/
    

RUN apk add --update build-base gcc musl-dev postgresql-dev libffi-dev
